#!/bin/bash
set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR/config.sh"

# 색상
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

ACTION=$1

usage() {
  echo "Usage: $0 {list|start|stop|terminate}"
  echo ""
  echo "Commands:"
  echo "  list       - Show all loadtest instances and their status"
  echo "  start      - Start stopped instances and update hosts.txt"
  echo "  stop       - Stop running instances (saves cost)"
  echo "  terminate  - DELETE all instances permanently (cannot undo!)"
  echo ""
  echo "Examples:"
  echo "  $0 list"
  echo "  $0 stop"
  echo "  $0 start"
  exit 1
}

case $ACTION in
  list)
    echo -e "${BLUE}Loadtest instances in $AWS_REGION:${NC}"
    echo ""
    aws ec2 describe-instances \
      --filters "Name=tag:Environment,Values=loadtest" \
      --query 'Reservations[*].Instances[*].[InstanceId,State.Name,PublicIpAddress,InstanceType,LaunchTime]' \
      --output table \
      --region $AWS_REGION
    ;;

  start)
    echo -e "${YELLOW}Starting all stopped loadtest instances...${NC}"

    INSTANCE_IDS=$(aws ec2 describe-instances \
      --filters "Name=tag:Environment,Values=loadtest" \
                "Name=instance-state-name,Values=stopped" \
      --query 'Reservations[*].Instances[*].InstanceId' \
      --output text \
      --region $AWS_REGION)

    if [ -z "$INSTANCE_IDS" ]; then
      echo -e "${YELLOW}No stopped instances found${NC}"
    else
      echo "Instance IDs: $INSTANCE_IDS"
      aws ec2 start-instances --instance-ids $INSTANCE_IDS --region $AWS_REGION

      echo ""
      echo -e "${YELLOW}Waiting for instances to be running...${NC}"
      aws ec2 wait instance-running --instance-ids $INSTANCE_IDS --region $AWS_REGION

      echo -e "${GREEN}✓ Instances started${NC}"

      # Public IP는 재할당되므로 hosts.txt 업데이트
      echo ""
      bash "$SCRIPT_DIR/update-hosts.sh"
    fi
    ;;

  stop)
    echo -e "${YELLOW}Stopping all running loadtest instances...${NC}"

    INSTANCE_IDS=$(aws ec2 describe-instances \
      --filters "Name=tag:Environment,Values=loadtest" \
                "Name=instance-state-name,Values=running" \
      --query 'Reservations[*].Instances[*].InstanceId' \
      --output text \
      --region $AWS_REGION)

    if [ -z "$INSTANCE_IDS" ]; then
      echo -e "${YELLOW}No running instances found${NC}"
    else
      echo "Instance IDs: $INSTANCE_IDS"
      aws ec2 stop-instances --instance-ids $INSTANCE_IDS --region $AWS_REGION

      echo -e "${GREEN}✓ Instances stopped${NC}"
      echo -e "${BLUE}Note: Public IPs will change when restarted. Run 'update-hosts.sh' after starting.${NC}"
    fi
    ;;

  terminate)
    echo -e "${RED}⚠️  WARNING: This will DELETE all loadtest instances permanently!${NC}"
    echo -e "${RED}⚠️  This action CANNOT be undone!${NC}"
    echo ""

    # 인스턴스 목록 보여주기
    aws ec2 describe-instances \
      --filters "Name=tag:Environment,Values=loadtest" \
      --query 'Reservations[*].Instances[*].[InstanceId,State.Name,InstanceType]' \
      --output table \
      --region $AWS_REGION

    echo ""
    read -p "Type 'yes' to confirm deletion: " CONFIRM

    if [ "$CONFIRM" = "yes" ]; then
      INSTANCE_IDS=$(aws ec2 describe-instances \
        --filters "Name=tag:Environment,Values=loadtest" \
        --query 'Reservations[*].Instances[*].InstanceId' \
        --output text \
        --region $AWS_REGION)

      if [ -z "$INSTANCE_IDS" ]; then
        echo -e "${YELLOW}No instances found${NC}"
      else
        aws ec2 terminate-instances --instance-ids $INSTANCE_IDS --region $AWS_REGION
        echo ""
        echo -e "${GREEN}✓ Instances terminated: $INSTANCE_IDS${NC}"

        # hosts.txt 초기화
        cat > "$SCRIPT_DIR/hosts.txt" <<EOF
# EC2 Public IP addresses (one per line)
# Auto-generated by setup-ec2.sh or update-hosts.sh
# You can also edit manually

# All instances have been terminated
EOF
      fi
    else
      echo "Cancelled"
    fi
    ;;

  *)
    usage
    ;;
esac
